# Generated by Django 3.2.4 on 2021-07-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_avatar'),
        ('users', '0002_alter_progress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
