# Generated by Django 3.2.4 on 2021-07-05 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_avatar'),
        ('session', '0002_session_enabled'),
        ('users', '0003_alter_progress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('user', 'last_session')},
        ),
    ]
