# Generated by Django 3.2.4 on 2021-07-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_solution'),
        ('authentication', '0008_alter_user_avatar'),
        ('users', '0004_auto_20210706_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('shown_hint', models.BooleanField(default=False)),
                ('solution_code', models.TextField()),
                ('draft_code', models.TextField()),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.solution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'unique_together': {('user', 'solution')},
            },
        ),
    ]
