# Generated by Django 3.2.4 on 2021-07-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_solutionprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionprogress',
            name='shown_solution',
            field=models.BooleanField(default=False),
        ),
    ]
