# Generated by Django 3.2.4 on 2021-07-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
