# Generated by Django 3.2.4 on 2021-06-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('googleId', models.CharField(max_length=21, unique=True)),
                ('avatar', models.CharField(max_length=43)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('firstName', models.CharField(max_length=254)),
                ('familyName', models.CharField(max_length=254)),
                ('created_on', models.DateTimeField()),
                ('xp', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
